default_platform(:android)

platform :android do
    desc "Distribute a new Android app build to Firebase App Distribution"
    lane :distribute do
      sh "flutter clean"
      sh "flutter build apk"
      release = firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID"], 
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_type:"APK",
      testers: "mohamednosair142@gmail.com, ahmed123@gmail.com ",
      release_notes: "Lots of amazing new features to test out!"
      )
    end
end